[package]
name = "concrusus"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.54", features = ["tcp-tokio", "dns-tokio", "quic"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
